obj-m := ipt_IPID.o bcm96358vw2_btn.o bcm96358vw2_gpio.o

bcm96358vw2_btn-y := button.o hotplug.o
bcm96358vw2_gpio-y := gpio.o

BCM_CFLAGS = -I$(BCMROOT)/bcmdrivers/broadcom/include/$(BRCM_BOARD) \
             -I$(BCMROOT)/bcmdrivers/opensource/include/$(BRCM_BOARD) \
             -I$(BCMROOT)/shared/opensource/include/$(BRCM_BOARD)

CFLAGS_button.o = $(BCM_CFLAGS)
CFLAGS_gpio.o = $(BCM_CFLAGS) -I$(M)/linux/include
