#!/bin/sh

KERNEL_VERSION=2.6.21.5

HOST_ARCH=`uname -m`
case $HOST_ARCH in 
    x86_64)
	    break;;
    *)
	    HOST_ARCH=i386;;
esac

TOPDIR=$PWD

rm -fr rootfs
mkdir rootfs
gzip -d < openwrt-brcm63xx-rootfs.cpio.gz | (cd rootfs && cpio -i)
rm -f  rootfs/init
rm -fr rootfs/etc/modules.d
rm -fr rootfs/lib/modules
rm -f  rootfs/usr/lib/opkg/lists/*
chmod 1777 rootfs/tmp
cd $TOPDIR/modules/lib/modules/$KERNEL_VERSION
cat $TOPDIR/config/kmod-broadcom.list $TOPDIR/config/kmod-base.list $TOPDIR/config/kmod-sched.list | \
    cpio -p -d $TOPDIR/rootfs/lib/modules/$KERNEL_VERSION
cd $TOPDIR/src/modules
cat $TOPDIR/config/kmod-local.list | \
	cpio -p -d $TOPDIR/rootfs/lib/modules/$KERNEL_VERSION
cd $TOPDIR/fs.custom
find | cpio -u -p -d ../rootfs

cd $TOPDIR
mknod rootfs/dev/console c 5 1
./tools/$HOST_ARCH/mksquashfs rootfs $1 -b 65536 -be -all-root

#	rm -fr rootfs/lib/firmware
#	rm -fr rootfs/etc/hotplug.d/atm
