#!/bin/sh

rm_comments() {
    sed -e 's/#.*//' -e 's/[ ^I]*$//' -e '/^$/d'
}

. ./Build.defs

TOPDIR="$PWD"

rm -fr rootfs
mkdir rootfs
gzip -d < "$IMAGEBUILDER/bin/brcm63xx/openwrt-brcm63xx-rootfs.cpio.gz" | (cd rootfs && cpio -i)
rm -f  rootfs/init
rm -fr rootfs/etc/modules.d
rm -fr rootfs/lib/modules
rm -f  rootfs/usr/lib/opkg/lists/*
mkdir -p rootfs/lib/functions/fsck # eliminate "WARNING: /lib/functions/fsck not found"
chmod +s rootfs/bin/busybox
chmod 1777 rootfs/tmp
cd "$BCMFW/targets/DSL-2760U/modules/lib/modules/$KERNEL_VERSION"

for LISTFILE in `ls -1 $TOPDIR/rootfs/usr/lib/opkg/info/kmod-*.list`
do
    LISTFILE=`basename $LISTFILE`
    PKGNAME=${LISTFILE%.list}
    rm_comments < $TOPDIR/config/mapping/$PKGNAME | cpio -p -d $TOPDIR/rootfs/lib/modules/$KERNEL_VERSION
done
cat $TOPDIR/config/kmod-broadcom \
	$TOPDIR/config/kmod-misc | \
    rm_comments | \
    cpio -p -d $TOPDIR/rootfs/lib/modules/$KERNEL_VERSION
cd $TOPDIR/modules
cat $TOPDIR/config/kmod-local | rm_comments | \
	cpio -p -d $TOPDIR/rootfs/lib/modules/$KERNEL_VERSION
cd $TOPDIR/fs.overlay
find | cpio -u -p -d ../rootfs

cd $TOPDIR
mknod rootfs/dev/console c 5 1
"$BCMFW"/hostTools/squashfs/mksquashfs rootfs $1 -b 65536 -be -all-root

#	rm -fr rootfs/lib/firmware
#	rm -fr rootfs/etc/hotplug.d/atm
