#!/bin/sh

installd() {
    local DESTDIR="$2/$1"
    if [ ! -e "$DESTDIR" ]; then
        echo "Creating directory: $DESTDIR"
        mkdir -p "$DESTDIR"
        return
    fi
    if [ ! -d "$DESTDIR" ]; then
        echo error: $DESTDIR exists, but not a directory.
        exit 1
    fi
}

installf() {
    local DESTFILE="$3/$1"
    if [ -e "$DESTFILE" ] || [ -h "$DESTFILE" ]; then
        rm -f "$DESTFILE"
    fi
    ln -s "$2/$1" "$DESTFILE"
}

lndir() {
    local SRCROOT="$1"
    local DESROOT="$2"
    (cd "$SRCROOT"; find *) | while read LINE 
    do
        if [ -d "$SRCROOT/$LINE" ]; then
            installd "$LINE" "$DESROOT"
        else
            echo "Overwriting $LINE"
            installf "$LINE" "$SRCROOT" "$DESROOT"
        fi
    done
}

. ./Build.defs

if [ -z "$1" ] || [ "$1" = all ] || [ "$1" = fw ]; then 
    if [ ! -e "$BCMFW/README" ]; then
        echo "fail to verify $BCMFW"
        exit 1
    fi
    echo "Processing DSL-2760U ..."
    lndir "$PWD/src/files" "$BCMFW"
fi

if [ -z "$1" ] || [ "$1" = all ] || [ "$1" = im ]; then 
    if [ ! -e "$IMAGEBUILDER/repositories.conf" ]; then
        echo "fail to verify $IMAGEBUILDER"
        exit 1
    fi
    echo "Processing ImageBuilder ..."
    lndir "$PWD/backfire/ImageBuilder" "$IMAGEBUILDER"
fi

echo Done.
