EXTRA_CFLAGS += -I$(M)/linux/include

ifneq (,$(macvlan))
	DEVMODS += macvlan.o
endif

obj-m := xt_connlimit.o bcm6358_enet.o $(DEVMODS)

bcm6358_enet-y := bcm63xx_enet.o clk.o dev-enet.o board_bcm963xx.o
