obj-m := ipt_IPID.o btn_hotplug.o

btn_hotplug-y := button.o hotplug.o

CFLAGS_button.o = -I$(BCMROOT)/bcmdrivers/broadcom/include/$(BRCM_BOARD) \
                  -I$(BCMROOT)/bcmdrivers/opensource/include/$(BRCM_BOARD) \
                  -I$(BCMROOT)/shared/opensource/include/$(BRCM_BOARD)

