EXTRA_CFLAGS += -I$(M)/linux/include -I$(M)/linux/arch/mips/include/asm/mach-bcm63xx \
                -DCONFIG_BCM63XX_CPU_6358

ifneq (,$(bcm63xx_enet))
	DEVMODS += bcm63xx_enet.o
endif
ifneq (,$(macvlan))
	DEVMODS += macvlan.o
endif

obj-m := xt_connlimit.o $(DEVMODS)
