include ../common.mk

EXTRA_CFLAGS += -I$(BCMPKG)/bcmdrivers/broadcom/include/$(BRCM_BOARD) \
		-I$(BCMPKG)/bcmdrivers/opensource/include/$(BRCM_BOARD) \
		-I$(BCMPKG)/shared/opensource/include/$(BRCM_BOARD)

obj-m := btn_hotplug.o

