EXTRA_CFLAGS += -I$(BCMROOT)/bcmdrivers/broadcom/include/$(BRCM_BOARD) \
		        -I$(BCMROOT)/bcmdrivers/opensource/include/$(BRCM_BOARD) \
				-I$(BCMROOT)/shared/opensource/include/$(BRCM_BOARD)

obj-m = btn_hotplug.o

btn_hotplug-y := button.o hotplug.o
