#!/bin/sh
#
# Author: Zhifeng Gu <guzhifeng1979@hotmail.com>
# Date: 2011/03
# License: GPL

BCMROOT=/bcm
EXEC=`basename $0`

export LD_LIBRARY_PATH=/lib:/$BCMROOT/lib:$BCMROOT/lib/private:$BCMROOT/lib/public
exec $BCMROOT/bin/$EXEC "$@"
